"""add repository service paths

Revision ID: 068ad808b96f
Revises: 68b8c0271d0e
Create Date: 2026-09-06 21:38:16.643427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '068ad808b96f'
down_revision: Union[str, None] = '68b8c0271d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('service_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'service_paths')
    # ### end Alembic commands ###
