"""add deploy blocking and compose state

Revision ID: 68b8c0271d0e
Revises: c2f6817295f7
Create Date: 2026-09-06 01:09:35.522304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '68b8c0271d0e'
down_revision: Union[str, None] = 'c2f6817295f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# `compose` is a new BuildMethod value; autogenerate never detects enum members.
def upgrade() -> None:
    op.execute("ALTER TYPE build_method ADD VALUE IF NOT EXISTS 'compose'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('suspension_reason', sa.String(length=500), nullable=True))
    op.add_column('deployments', sa.Column('compose_project', sa.String(length=128), nullable=True))
    op.add_column('deployments', sa.Column('compose_services', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('can_deploy', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('deploy_block_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deploy_block_reason')
    op.drop_column('users', 'can_deploy')
    op.drop_column('deployments', 'compose_services')
    op.drop_column('deployments', 'compose_project')
    op.drop_column('deployments', 'suspension_reason')
    # ### end Alembic commands ###
