"""add runtime state, events, quotas

Revision ID: c2f6817295f7
Revises: 5ddac389328c
Create Date: 2026-09-05 23:50:13.069158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c2f6817295f7'
down_revision: Union[str, None] = '5ddac389328c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Statuses added in this revision. Alembic's autogenerate never detects new
# enum members, so they are spelled out here. `ALTER TYPE ... ADD VALUE` is
# allowed inside a transaction on PostgreSQL 12+ as long as the new value is
# not *used* in the same transaction — nothing here does.
NEW_STATUSES = ("pushing", "starting", "stopped")


def upgrade() -> None:
    for value in NEW_STATUSES:
        op.execute(
            f"ALTER TYPE deployment_status ADD VALUE IF NOT EXISTS '{value}'"
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Enum('info', 'success', 'warning', 'error', name='event_level'), server_default='info', nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_events_deployment_id'), 'deployment_events', ['deployment_id'], unique=False)
    op.add_column('deployments', sa.Column('container_name', sa.String(length=128), nullable=True))
    op.add_column('deployments', sa.Column('app_port', sa.Integer(), nullable=True))
    op.add_column('deployments', sa.Column('runtime_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deployments', sa.Column('runtime_stopped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deployments', sa.Column('suspended_by_admin', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_deployments_subdomain'), 'deployments', ['subdomain'], unique=True)
    op.add_column('users', sa.Column('max_deployments', sa.Integer(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_deployments')
    op.drop_index(op.f('ix_deployments_subdomain'), table_name='deployments')
    op.drop_column('deployments', 'suspended_by_admin')
    op.drop_column('deployments', 'runtime_stopped_at')
    op.drop_column('deployments', 'runtime_started_at')
    op.drop_column('deployments', 'app_port')
    op.drop_column('deployments', 'container_name')
    op.drop_index(op.f('ix_deployment_events_deployment_id'), table_name='deployment_events')
    op.drop_table('deployment_events')
    op.execute("DROP TYPE IF EXISTS event_level")
    # ### end Alembic commands ###
    # The added deployment_status values are deliberately not removed:
    # PostgreSQL cannot drop an enum member, and recreating the type would
    # require rewriting every row that uses it.
